AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  English Learning Platform API - A serverless microservice for English language learning features including
  word evaluation, reading comprehension, and writing assessment using AI capabilities.

Globals:
  Function:
    Timeout: 29

Resources:
  # Shared Lambda layer for dependencies
  EnglishLearningDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: EnglishLearningDependencies
      Description: "Dependencies for English Learning Platform (openai)"
      ContentUri: dependencies_layer/
      CompatibleRuntimes:
        - python3.12

  # API Gateway with CORS configuration
  EnglishLearningApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # Word Evaluation Lambda Function
  WordEvaluatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WordEvaluator
      Handler: handlers/word_evaluator.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Layers:
        - !Ref EnglishLearningDependenciesLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: "arn:aws:ssm:*:*:parameter/EnglishLearning/OPENAI_API_KEY"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EnglishLearningApi
            Path: /api/v1/word-evaluator
            Method: post
        OptionsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EnglishLearningApi
            Path: /api/v1/word-evaluator
            Method: options

  # Reading Generator Lambda Function
  ReadingGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReadingGenerator
      Handler: handlers/reading_generator.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Layers:
        - !Ref EnglishLearningDependenciesLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: "arn:aws:ssm:*:*:parameter/EnglishLearning/OPENAI_API_KEY"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EnglishLearningApi
            Path: /api/v1/reading-generator
            Method: get
        OptionsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EnglishLearningApi
            Path: /api/v1/reading-generator
            Method: options

  # Writing Evaluator Lambda Function
  WritingEvaluatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WritingEvaluator
      Handler: handlers/writing_evaluator.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Layers:
        - !Ref EnglishLearningDependenciesLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: "arn:aws:ssm:*:*:parameter/EnglishLearning/OPENAI_API_KEY"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EnglishLearningApi
            Path: /api/v1/writing-evaluator
            Method: post
        OptionsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EnglishLearningApi
            Path: /api/v1/writing-evaluator
            Method: options

Outputs:
  ApiEndpoint:
    Description: "English Learning Platform API Base URL"
    Value: !Sub "https://${EnglishLearningApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  WordEvaluatorEndpoint:
    Description: "Word Evaluator API Endpoint"
    Value: !Sub "https://${EnglishLearningApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/word-evaluator"
  ReadingGeneratorEndpoint:
    Description: "Reading Generator API Endpoint"
    Value: !Sub "https://${EnglishLearningApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/reading-generator"
  WritingEvaluatorEndpoint:
    Description: "Writing Evaluator API Endpoint"
    Value: !Sub "https://${EnglishLearningApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/writing-evaluator"